version: '3'
services:
  apache:
    build: ./documentation
    container_name: apache2-php
    volumes:
      - ./documentation/.htaccess:/usr/local/apache2/htdocs/.htaccess
      - ./html:/usr/local/apache2/htdocs/
      - ./html:/var/www/html
    env_file:
    - .env
    ports:
      - "8090:80"
    depends_on:
      - mysql
    restart: unless-stopped
  mysql:
    image: mysql:latest
    container_name: mysql-db
    env_file:
    - .env
    volumes:
      - ./mysql:/var/lib/mysql
    restart: unless-stopped

  go-api:
    build: ./go-api
    container_name: go-api-app
    ports:
      - "8091:8090"
    restart: unless-stopped
  
