version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: nginx_server
    env_file:
      - .env
    ports:
      - "87:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./src:/var/www/html
    depends_on:
      - php
      - mysql

  php:
    build:
      context: . # Directory with the Dockerfile
      dockerfile: dockerfile
    container_name: php_server
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql_server
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${db_root_password}
      - MYSQL_DATABASE=${db_name}
      - MYSQL_USER=${db_user}
      - MYSQL_PASSWORD=${db_password}
