version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: nginx_server
    env_file:
      - .env
    environment:
      - db_host=${db_host}
      - db_name=${db_name}
      - db_user=${db_user}
      - db_password=${db_password}
    ports:
      - "87:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./src:/var/www/html
    depends_on:
      - php
      - mysql

  php:
    image: php:8.0-fpm
    container_name: php_server
    volumes:
      - ./src:/var/www/html
  mysql:
    image: mysql:latest
    container_name: mysql_server
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${db_root_password}
      - MYSQL_DATABASE=${db_name}
      - MYSQL_USER=${db_user}
      - MYSQL_PASSWORD=${db_password}
    volumes:
      - mysql_data:/var/lib/mysql

# Declare the named volume here
volumes:
  mysql_data:
